#!/bin/bash
cd /g/data/u46/users/sa9525/digitalearthau/docs/sandpit/Tmp
jupyter nbconvert --execute find_bom_rainfall_grids_metadata.ipynb
jupyter nbconvert --execute find_dsm1sv10_metadata.ipynb
jupyter nbconvert --execute find_gamma_ray_metadata.ipynb
jupyter nbconvert --execute find_high_tide_comp_20p_metadata.ipynb
jupyter nbconvert --execute find_high_tide_comp_count_metadata.ipynb
jupyter nbconvert --execute find_item_v2_metadata.ipynb
jupyter nbconvert --execute find_item_v2_conf_metadata.ipynb
jupyter nbconvert --execute find_low_tide_comp_20p_metadata.ipynb
jupyter nbconvert --execute find_low_tide_comp_count_metadata.ipynb
jupyter nbconvert --execute find_ls5_fc_albers_metadata.ipynb
jupyter nbconvert --execute find_ls5_fc_albers_archived_metadata.ipynb
jupyter nbconvert --execute find_ls5_level1_scene_metadata.ipynb
jupyter nbconvert --execute find_ls5_nbar_albers_metadata.ipynb
jupyter nbconvert --execute find_ls5_nbar_scene_metadata.ipynb
jupyter nbconvert --execute find_ls5_nbart_albers_metadata.ipynb
jupyter nbconvert --execute find_ls5_nbart_scene_metadata.ipynb
jupyter nbconvert --execute find_ls5_ndvi_albers_metadata.ipynb
jupyter nbconvert --execute find_ls5_pq_albers_metadata.ipynb
jupyter nbconvert --execute find_ls5_pq_scene_metadata.ipynb
jupyter nbconvert --execute find_ls5_satellite_telemetry_data_metadata.ipynb
jupyter nbconvert --execute find_ls7_fc_albers_metadata.ipynb
jupyter nbconvert --execute find_ls7_fc_albers_archived_metadata.ipynb
jupyter nbconvert --execute find_ls7_fc_albers_staging_metadata.ipynb
jupyter nbconvert --execute find_ls7_level1_scene_metadata.ipynb
jupyter nbconvert --execute find_ls7_nbar_albers_metadata.ipynb
jupyter nbconvert --execute find_ls7_nbar_scene_metadata.ipynb
jupyter nbconvert --execute find_ls7_nbart_albers_metadata.ipynb
jupyter nbconvert --execute find_ls7_nbart_scene_metadata.ipynb
jupyter nbconvert --execute find_ls7_ndvi_albers_metadata.ipynb
jupyter nbconvert --execute find_ls7_pq_albers_metadata.ipynb
jupyter nbconvert --execute find_ls7_pq_scene_metadata.ipynb
jupyter nbconvert --execute find_ls7_satellite_telemetry_data_metadata.ipynb
jupyter nbconvert --execute find_ls8_fc_albers_metadata.ipynb
jupyter nbconvert --execute find_ls8_fc_albers_archived_metadata.ipynb
jupyter nbconvert --execute find_ls8_level1_oli_scene_metadata.ipynb
jupyter nbconvert --execute find_ls8_level1_scene_metadata.ipynb
jupyter nbconvert --execute find_ls8_nbar_albers_metadata.ipynb
jupyter nbconvert --execute find_ls8_nbar_oli_albers_metadata.ipynb
jupyter nbconvert --execute find_ls8_nbar_oli_scene_metadata.ipynb
jupyter nbconvert --execute find_ls8_nbar_scene_metadata.ipynb
jupyter nbconvert --execute find_ls8_nbart_albers_metadata.ipynb
jupyter nbconvert --execute find_ls8_nbart_oli_albers_metadata.ipynb
jupyter nbconvert --execute find_ls8_nbart_oli_scene_metadata.ipynb
jupyter nbconvert --execute find_ls8_nbart_scene_metadata.ipynb
jupyter nbconvert --execute find_ls8_ndvi_albers_metadata.ipynb
jupyter nbconvert --execute find_ls8_pq_albers_metadata.ipynb
jupyter nbconvert --execute find_ls8_pq_oli_scene_metadata.ipynb
jupyter nbconvert --execute find_ls8_pq_scene_metadata.ipynb
jupyter nbconvert --execute find_ls8_satellite_telemetry_data_metadata.ipynb
jupyter nbconvert --execute find_modis_mcd43a1_tile_metadata.ipynb
jupyter nbconvert --execute find_modis_mcd43a2_tile_metadata.ipynb
jupyter nbconvert --execute find_modis_mcd43a3_tile_metadata.ipynb
jupyter nbconvert --execute find_modis_mcd43a4_tile_metadata.ipynb
jupyter nbconvert --execute find_srtm_dem1sv1_0_metadata.ipynb
jupyter nbconvert --execute find_wofs_albers_metadata.ipynb
jupyter nbconvert --execute find_wofs_modified_albers2_metadata.ipynb
